.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TERRIBLE_TWOS" "1" "November 2013" "" ""
.
.SH "NAME"
\fBterrible_twos\fR
.
.P
terrible_twos(1) \-\- drill Scrabble\'s two\-letter words
.
.SH "SYNOPSIS"
\fBterrible_twos\fR
.
.SH "DESCRIPTION"
\fBterrible_twos\fR is a command\-line tool to improve your recollection of Scrabble\'s two\-letter words\.
