#!/usr/bin/env ruby
require 'methadone'
require_relative 'lib/terrible_twos'
require_relative 'app/controller'
require_relative 'lib/drill'

class TerribleTwos
  def initialize
    @drill = Drill.new
    @controller = Controller.new @drill
  end

  def run
    @controller.run
  end

end

include Methadone::Main
include Methadone::CLILogging

main do |board|
  TerribleTwos.new.run
end

on '-b BOARD', '--board', 'Drill just one board'

go!
