#!/usr/bin/env ruby
require_relative 'app/controller'

class TerribleTwos
  def initialize
    @drill = Drill.new
    @controller = Controller.new @drill
  end

  def run
    @controller.run
  end

end

TerribleTwos.new.run
